version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: nest_postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '8000:8000'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nest_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: nest_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - nest_network

  redis:
    image: redis:7.0-alpine
    container_name: nest_redis
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    networks:
      - nest_network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: nest_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'
    networks:
      - nest_network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: nest_kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_LISTENERS: ${KAFKA_LISTENERS}
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_ZOOKEEPER_CONNECT: 'nest_zookeeper:2181'
    ports:
      - '9092:9092'
    networks:
      - nest_network

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_app
    env_file: .env
    environment:
      DATABASE_HOST: postgres
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - nest_network

volumes:
  postgres_data:

networks:
  nest_network:
